const a = parseInt("16 volts", 10);
console.log(a);
const b = parseInt("3a", 16);
const c = parseInt("3a", 10);
console.log(b);
console.log(c);
const d = parseFloat("15.5 kph");
console.log(d);
const e = new Date();
console.log(e);
console.log(e.toString());
const ts = e.valueOf();
console.log(ts);
